name: 'Deploy To Netlify'
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest  
    defaults:
      run:
        working-directory: /
    steps:
    - name: build app
      run:  yarn build && yarn export

  
