name: 'Deploy To Netlify'
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest  
    steps:
    - name: build app
      run:
          cd spacebar/spacebar
          yarn build && yarn export

  
