name: 'Deploy To Netlify'
on:
  push:
    branches:
      - main
jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest  
    defaults:
      run:
        working-directory: /
    steps:
    - name: build app
      run:  npm run build && npm export

  
