name: Upload

on: push

jobs:
  upload:
    name: Compile and upload LaTeX document to Netlify.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: MrFlynn/upload-to-netlify-action@v2
        with:
          source-file: "_static"
          destination-path: "/"
          site-name: olidental
          netlify-token: ${{ secrets.NETLIFY_TOKEN }}
